# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ShengJianBao' do
	pod 'AlamofireObjectMapper', '~> 2.1'
	pod 'ObjectMapper', '~> 1.0'
	pod 'Alamofire', '~> 3.0'
    pod "CYLTabBarController"
    pod "UITableView+FDTemplateLayoutCell", "1.4.beta"
    pod "MJRefresh"
    pod "CYPullRefresh"
    pod 'IQKeyboardManagerSwift'
    pod 'SnapKit', '~> 0.15.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'PINCache',:git => 'git@github.com:pinterest/PINCache.git'
    pod 'TPKeyboardAvoiding', '~> 1.2.11'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'BlocksKit', '~> 2.2.5'
end
